### ISSUE TITLE
Tea-tree release plans

### ISSUE THREAD

**Issue by movefasta** [the-sett/tea-tree#1]
Hello.
Have you any kind of roadmap to release this package? Can i help you to make release sooner ?

**Comment by rupertlssmith** [comment]
Hi, Yes I plan to release it soon. I am currently converting the example to 0.19 - it doesn't require much more work, so I should be able to publish it in the next few days.

Would be interested to hear about your use case?

**Comment by movefasta** [comment]
My case is similar to yours, described in discourse.elm-lang.org [topic](https://discourse.elm-lang.org/t/update-a-node-in-a-tree/1401/13). I have a big tree rendered in html-view, whose nodes should be moved or updated very often(without adding or deleting new nodes). Besides updating nodes in a model, my app should updates all nodes in path (calculate new hashes in a ipfs merkle-tree) through a bunch of http requests and update nodes again. I guess stale problem will probably happens(or maybe i dont understand ?). I dont wanna block user while updating tree. So I found your implementation of tree data structure most effective in this case.
In beginning i tried to use https://github.com/turboMaCk/lazy-tree-with-zipper , but that tree implementation dont allow me to debug tree in a embedded elm-debugger, so i  switched to https://package.elm-lang.org/packages/zwilias/elm-rosetree/1.2.2/ . In zwilias's rose tree i got some troubles in efficient. Tree updated too slowly.
Now i'm [use](https://github.com/movefasta/elm-suz-dal/blob/stylish-elephants-view-refactor/src/View.elm) Tree.indexedMap. My tree don't change structure while loaded once and maybe after some refactoring i found my app is enough efficient, but now i know more efficient way in your package... +)

**Comment by rupertlssmith** [comment]
In my case, I have a tree structured document which represents 'content' loaded from a content management system. In editing mode the 'content' becomes interactive; for example the mouse will highlight all editable content as it passes over it. It is possible for mouse in/out events to overlap and be stale, so this is really what I wrote this for.
Sounds like it will fit your use-case too, you could haver user interaction and HTTP requests happen simultanesouly leading to stale events.

**Comment by rupertlssmith** [comment]
I just pushed version 1.0.0 to package.elm-lang.org.

**Comment by movefasta** [comment]
Thanks a lot. I'll try your package instead of rose-tree and give you some feedback
